# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    env_file:
      - .env
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    ports:
      - 3306:3306 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
